image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2/

maven-build:
  stage: build
  script: mvn compile

maven-test:
  stage: test
  script: mvn test
  dependencies:
  - maven-build

maven-deploy:
  stage: deploy
  script: mvn package
  dependencies:
  - maven-test
  artifacts:
    paths:
    - target/TalkingMobs.jar
  only:
    - tags