# The maximum distance between a mob and a player (0 = any)
# Only players in this range to the talking mob will see the message
maxDistance: 0

# The maximum distance between a mob and a player to send "looking" messages
max-looking-distance: 10

# The time in milliseconds to wait before sending another message for the same mob to the same player for the same event
spam-timeout: 3000

# Define which events should show messages
# Everything except for "spawned" is a boolean (true or false).
# The "spawned" event expects a list of spawn reasons (see https://jd.bukkit.org/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html for possible spawn reasons).
events:
  attacked: true
  interacted: true
  killed: true
  looking: true
  spawned:
  - CUSTOM
  - SPAWNER
  - SPAWNER_EGG
  tamed: true

# How to format the messages
# %mobname% is replaced with the name of the talking mob
# %message% is replaced with the message
# %event% is replaced with the event type (e.g. attacked, interacted, killed, spawned or tamed)
messageFormat:
  default: "[&a%mobname%&r] %message%"
#  looking: "[&a%mobname%&r] %message%"
#  attacked: "[&a%mobname%&r] %message%"
#  interacted: "[&a%mobname%&r] %message%"
#  killed: "[&a%mobname%&r] &c%message%"
#  looking: "[&a%mobname%&r] &c%message%"
#  spawned: "[&a%mobname%&r] %message%"
#  tamed: "[&a%mobname%&r] %message%"