name: TalkingMobs
version: ${project.version}
description: '${project.description}'
author: Programie
website: ${project.url}
main: com.selfcoders.talkingmobs.TalkingMobs
commands:
  talkingmobs:
    description: 'Command for actions of Talking Mobs'
    permission: talkingmobs
    usage: 'Use /talkingmobs help for help'
permissions:
  talkingmobs.*:
    description: 'Gives access to all features'
    children:
      talkingmobs: true
      talkingmobs.receive: true
      talkingmobs.reload: true
  talkingmobs:
    description: 'Allow access to the /talkingmobs command'
    default: true
  talkingmobs.receive:
    description: 'Receive mob messages'
    default: true
  talkingmobs.reload:
    description: 'Allows to reload the plugin configuration'